'''
Created on Monday, 06 April 2020
@author: wbs0013

THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT!!!

XML Source: /home/wbs0013/fprime/Svc/CmdDispatcher/CommandDispatcherComponentAi.xml
'''

# Import the types this way so they do not need prefixing for execution.
from fprime.common.models.serialize.type_exceptions import *
from fprime.common.models.serialize.type_base import *

from fprime.common.models.serialize.bool_type import *
from fprime.common.models.serialize.enum_type import *
from fprime.common.models.serialize.f32_type import *
from fprime.common.models.serialize.f64_type import *

from fprime.common.models.serialize.u8_type import *
from fprime.common.models.serialize.u16_type import *
from fprime.common.models.serialize.u32_type import *
from fprime.common.models.serialize.u64_type import *

from fprime.common.models.serialize.i8_type import *
from fprime.common.models.serialize.i16_type import *
from fprime.common.models.serialize.i32_type import *
from fprime.common.models.serialize.i64_type import *

from fprime.common.models.serialize.string_type import *
from fprime.common.models.serialize.serializable_type import *

from fprime_gds.common.models.common import event
# Each file represents the information for a single event
# These module variables are used to instance the event object within the Gse


COMPONENT = "Svc::CommandDispatcher"

NAME = "OpCodeError"
ID  = 0x7c
SEVERITY = "WARNING_HI"
FORMAT_STRING = "Opcode 0x%04X completed with error %s "
EVENT_DESCRIPTION = "Op code completed with error event"

# Set arguments list with default values here.
ARGUMENTS = [
    ("Opcode","The opcode with the error",U32Type()),
    ("error","The error value",EnumType("ErrorResponse",{"ERR_INVALID_OPCODE":0,"ERR_VALIDATION_ERROR":1,"ERR_FORMAT_ERROR":2,"ERR_EXECUTION_ERROR":3,"ERR_BUSY":4,"ERR_UNEXP":5,})),
    ]

