'''
Created on Thursday, 26 March 2020
@author: wbs0013

THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT!!!

XML Source: /home/wbs0013/fprime/Svc/CmdDispatcher/CommandDispatcherComponentAi.xml
'''

# Import the types this way so they do not need prefixing for execution.
from fprime.common.models.serialize.type_exceptions import *
from fprime.common.models.serialize.type_base import *

from fprime.common.models.serialize.bool_type import *
from fprime.common.models.serialize.enum_type import *
from fprime.common.models.serialize.f32_type import *
from fprime.common.models.serialize.f64_type import *

from fprime.common.models.serialize.u8_type import *
from fprime.common.models.serialize.u16_type import *
from fprime.common.models.serialize.u32_type import *
from fprime.common.models.serialize.u64_type import *

from fprime.common.models.serialize.i8_type import *
from fprime.common.models.serialize.i16_type import *
from fprime.common.models.serialize.i32_type import *
from fprime.common.models.serialize.i64_type import *

from fprime.common.models.serialize.string_type import *
from fprime.common.models.serialize.serializable_type import *

from fprime_gds.common.models.common import event
# Each file represents the information for a single event
# These module variables are used to instance the event object within the Gse


COMPONENT = "Svc::CommandDispatcher"

NAME = "TestCmd1Args"
ID  = 0x82
SEVERITY = "ACTIVITY_HI"
FORMAT_STRING = "TEST_CMD_1 args: I32: %d, F32: %f, U8: %d"
EVENT_DESCRIPTION = "This log event message returns the TEST_CMD_1 arguments."

# Set arguments list with default values here.
ARGUMENTS = [
    ("arg1","Arg1",I32Type()),
    ("arg2","Arg2",F32Type()),
    ("arg3","Arg3",U8Type()),
    ]

