'''
Created on Wednesday, 25 March 2020
@author: wbs0013

THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT!!!

XML Source: PacketStatSerializableAi.xml
'''


# Import the types this way so they do not need prefixing for execution.
from fprime.common.models.serialize.type_exceptions import *
from fprime.common.models.serialize.type_base import *

from fprime.common.models.serialize.bool_type import *
from fprime.common.models.serialize.enum_type import *
from fprime.common.models.serialize.f32_type import *
from fprime.common.models.serialize.f64_type import *

from fprime.common.models.serialize.u8_type import *
from fprime.common.models.serialize.u16_type import *
from fprime.common.models.serialize.u32_type import *
from fprime.common.models.serialize.u64_type import *

from fprime.common.models.serialize.i8_type import *
from fprime.common.models.serialize.i16_type import *
from fprime.common.models.serialize.i32_type import *
from fprime.common.models.serialize.i64_type import *

from fprime.common.models.serialize.string_type import *
from fprime.common.models.serialize.serializable_type import *


class PacketStat(SerializableType):


    def __init__(self):
    
        m_list = [
            ("BuffRecv",U32Type(),"%u"),
            ("BuffErr",U32Type(),"%u"),
            ("PacketStatus",EnumType("PacketRecvStatus",{"PACKET_STATE_NO_PACKETS":0,"PACKET_STATE_OK":1,"PACKET_STATE_ERRORS":3,}),"%s"),
        ]
        
        super(PacketStat,self).__init__("PacketStat",m_list)
                    

